name: Cypress 

on: push 

jobs: 
  install:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Cypress install 
        uses: cypress-io/github-action@v6 
        with:
          runTests: false 

      - run: yarn cypress info 
      - run: node --version 
      - run: yarn build:ci
      

      - name: Save build folder 
        uses: actions/upload-artifact@v4
        with:
          name: dist 
          if-no-files-found: error 
          path: dist  

  cypress-run:
    runs-on: ubuntu-latest 
    needs: install 
    steps:
      - name: Checkout 
        uses: actions/checkout@v4 

      - name: Download the build folder 
        uses: actions/download-artifact@v4 
        with:
          name: dist 
          path: dist 
      
      - name: Node info 
        run: node -v

      - name: Cypress run 
        uses: cypress-io/github-action@v6
        with:
          build: yarn cypress info 
          start: yarn preview 
          wait-on: "http://localhost:5173"
          wait-on-timeout: 120 
          browser: chrome
          record: true 
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
        
